FROM golang:1.6
MAINTAINER ipfans <ipfanscn@gmail.com>

# goconvey && golint
RUN go get -u -v github.com/smartystreets/goconvey
RUN go get -u -v github.com/golang/lint/golint
RUN go get -u -v github.com/axw/gocov/gocov